name: fack.news
description: Reliable and independent news since 1982.
avatar: https://fack.news/favicon.ico
footer-links:
  email: contact@fack.news
  github: timmyrs/fack.news
  rss: yes
  twitter: timspeckhals
disqus: facknews
url: https://fack.news
baseurl: ""
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - LICENSE
  - README.md
  - CNAME
